// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/fmsmoov.proto

#ifndef PROTOBUF_proto_2ffmsmoov_2eproto__INCLUDED
#define PROTOBUF_proto_2ffmsmoov_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3003000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3003000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
namespace fmsmoov {
class ProcessorLiveData;
class ProcessorLiveDataDefaultTypeInternal;
extern ProcessorLiveDataDefaultTypeInternal _ProcessorLiveData_default_instance_;
}  // namespace fmsmoov

namespace fmsmoov {

namespace protobuf_proto_2ffmsmoov_2eproto {
// Internal implementation detail -- do not call these.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[];
  static const ::google::protobuf::uint32 offsets[];
  static void InitDefaultsImpl();
  static void Shutdown();
};
void AddDescriptors();
void InitDefaults();
}  // namespace protobuf_proto_2ffmsmoov_2eproto

// ===================================================================

class ProcessorLiveData : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:fmsmoov.ProcessorLiveData) */ {
 public:
  ProcessorLiveData();
  virtual ~ProcessorLiveData();

  ProcessorLiveData(const ProcessorLiveData& from);

  inline ProcessorLiveData& operator=(const ProcessorLiveData& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const ProcessorLiveData& default_instance();

  static inline const ProcessorLiveData* internal_default_instance() {
    return reinterpret_cast<const ProcessorLiveData*>(
               &_ProcessorLiveData_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    0;

  void Swap(ProcessorLiveData* other);

  // implements Message ----------------------------------------------

  inline ProcessorLiveData* New() const PROTOBUF_FINAL { return New(NULL); }

  ProcessorLiveData* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const ProcessorLiveData& from);
  void MergeFrom(const ProcessorLiveData& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(ProcessorLiveData* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // float inL = 1;
  void clear_inl();
  static const int kInLFieldNumber = 1;
  float inl() const;
  void set_inl(float value);

  // float inR = 2;
  void clear_inr();
  static const int kInRFieldNumber = 2;
  float inr() const;
  void set_inr(float value);

  // float outL = 3;
  void clear_outl();
  static const int kOutLFieldNumber = 3;
  float outl() const;
  void set_outl(float value);

  // float outR = 4;
  void clear_outr();
  static const int kOutRFieldNumber = 4;
  float outr() const;
  void set_outr(float value);

  // @@protoc_insertion_point(class_scope:fmsmoov.ProcessorLiveData)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  float inl_;
  float inr_;
  float outl_;
  float outr_;
  mutable int _cached_size_;
  friend struct protobuf_proto_2ffmsmoov_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// ProcessorLiveData

// float inL = 1;
inline void ProcessorLiveData::clear_inl() {
  inl_ = 0;
}
inline float ProcessorLiveData::inl() const {
  // @@protoc_insertion_point(field_get:fmsmoov.ProcessorLiveData.inL)
  return inl_;
}
inline void ProcessorLiveData::set_inl(float value) {
  
  inl_ = value;
  // @@protoc_insertion_point(field_set:fmsmoov.ProcessorLiveData.inL)
}

// float inR = 2;
inline void ProcessorLiveData::clear_inr() {
  inr_ = 0;
}
inline float ProcessorLiveData::inr() const {
  // @@protoc_insertion_point(field_get:fmsmoov.ProcessorLiveData.inR)
  return inr_;
}
inline void ProcessorLiveData::set_inr(float value) {
  
  inr_ = value;
  // @@protoc_insertion_point(field_set:fmsmoov.ProcessorLiveData.inR)
}

// float outL = 3;
inline void ProcessorLiveData::clear_outl() {
  outl_ = 0;
}
inline float ProcessorLiveData::outl() const {
  // @@protoc_insertion_point(field_get:fmsmoov.ProcessorLiveData.outL)
  return outl_;
}
inline void ProcessorLiveData::set_outl(float value) {
  
  outl_ = value;
  // @@protoc_insertion_point(field_set:fmsmoov.ProcessorLiveData.outL)
}

// float outR = 4;
inline void ProcessorLiveData::clear_outr() {
  outr_ = 0;
}
inline float ProcessorLiveData::outr() const {
  // @@protoc_insertion_point(field_get:fmsmoov.ProcessorLiveData.outR)
  return outr_;
}
inline void ProcessorLiveData::set_outr(float value) {
  
  outr_ = value;
  // @@protoc_insertion_point(field_set:fmsmoov.ProcessorLiveData.outR)
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)


}  // namespace fmsmoov

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_proto_2ffmsmoov_2eproto__INCLUDED
