// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/fmsmoov.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "proto/fmsmoov.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace fmsmoov {
class ProcessorLiveDataDefaultTypeInternal : public ::google::protobuf::internal::ExplicitlyConstructed<ProcessorLiveData> {
} _ProcessorLiveData_default_instance_;

namespace protobuf_proto_2ffmsmoov_2eproto {


namespace {

::google::protobuf::Metadata file_level_metadata[1];

}  // namespace

PROTOBUF_CONSTEXPR_VAR ::google::protobuf::internal::ParseTableField
    const TableStruct::entries[] = {
  {0, 0, 0, ::google::protobuf::internal::kInvalidMask, 0, 0},
};

PROTOBUF_CONSTEXPR_VAR ::google::protobuf::internal::AuxillaryParseTableField
    const TableStruct::aux[] = {
  ::google::protobuf::internal::AuxillaryParseTableField(),
};
PROTOBUF_CONSTEXPR_VAR ::google::protobuf::internal::ParseTable const
    TableStruct::schema[] = {
  { NULL, NULL, 0, -1, -1, false },
};

const ::google::protobuf::uint32 TableStruct::offsets[] = {
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ProcessorLiveData, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ProcessorLiveData, inl_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ProcessorLiveData, inr_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ProcessorLiveData, outl_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ProcessorLiveData, outr_),
};

static const ::google::protobuf::internal::MigrationSchema schemas[] = {
  { 0, -1, sizeof(ProcessorLiveData)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&_ProcessorLiveData_default_instance_),
};

namespace {

void protobuf_AssignDescriptors() {
  AddDescriptors();
  ::google::protobuf::MessageFactory* factory = NULL;
  AssignDescriptors(
      "proto/fmsmoov.proto", schemas, file_default_instances, TableStruct::offsets, factory,
      file_level_metadata, NULL, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 1);
}

}  // namespace

void TableStruct::Shutdown() {
  _ProcessorLiveData_default_instance_.Shutdown();
  delete file_level_metadata[0].reflection;
}

void TableStruct::InitDefaultsImpl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::internal::InitProtobufDefaults();
  _ProcessorLiveData_default_instance_.DefaultConstruct();
}

void InitDefaults() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &TableStruct::InitDefaultsImpl);
}
void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] = {
      "\n\023proto/fmsmoov.proto\022\007fmsmoov\"I\n\021Proces"
      "sorLiveData\022\013\n\003inL\030\001 \001(\002\022\013\n\003inR\030\002 \001(\002\022\014\n"
      "\004outL\030\003 \001(\002\022\014\n\004outR\030\004 \001(\002b\006proto3"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 113);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "proto/fmsmoov.proto", &protobuf_RegisterTypes);
  ::google::protobuf::internal::OnShutdown(&TableStruct::Shutdown);
}

void AddDescriptors() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;

}  // namespace protobuf_proto_2ffmsmoov_2eproto


// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int ProcessorLiveData::kInLFieldNumber;
const int ProcessorLiveData::kInRFieldNumber;
const int ProcessorLiveData::kOutLFieldNumber;
const int ProcessorLiveData::kOutRFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

ProcessorLiveData::ProcessorLiveData()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    protobuf_proto_2ffmsmoov_2eproto::InitDefaults();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:fmsmoov.ProcessorLiveData)
}
ProcessorLiveData::ProcessorLiveData(const ProcessorLiveData& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::memcpy(&inl_, &from.inl_,
    reinterpret_cast<char*>(&outr_) -
    reinterpret_cast<char*>(&inl_) + sizeof(outr_));
  // @@protoc_insertion_point(copy_constructor:fmsmoov.ProcessorLiveData)
}

void ProcessorLiveData::SharedCtor() {
  ::memset(&inl_, 0, reinterpret_cast<char*>(&outr_) -
    reinterpret_cast<char*>(&inl_) + sizeof(outr_));
  _cached_size_ = 0;
}

ProcessorLiveData::~ProcessorLiveData() {
  // @@protoc_insertion_point(destructor:fmsmoov.ProcessorLiveData)
  SharedDtor();
}

void ProcessorLiveData::SharedDtor() {
}

void ProcessorLiveData::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* ProcessorLiveData::descriptor() {
  protobuf_proto_2ffmsmoov_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_proto_2ffmsmoov_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const ProcessorLiveData& ProcessorLiveData::default_instance() {
  protobuf_proto_2ffmsmoov_2eproto::InitDefaults();
  return *internal_default_instance();
}

ProcessorLiveData* ProcessorLiveData::New(::google::protobuf::Arena* arena) const {
  ProcessorLiveData* n = new ProcessorLiveData;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void ProcessorLiveData::Clear() {
// @@protoc_insertion_point(message_clear_start:fmsmoov.ProcessorLiveData)
  ::memset(&inl_, 0, reinterpret_cast<char*>(&outr_) -
    reinterpret_cast<char*>(&inl_) + sizeof(outr_));
}

bool ProcessorLiveData::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:fmsmoov.ProcessorLiveData)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // float inL = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(13u)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 input, &inl_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // float inR = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(21u)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 input, &inr_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // float outL = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(29u)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 input, &outl_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // float outR = 4;
      case 4: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(37u)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 input, &outr_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:fmsmoov.ProcessorLiveData)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:fmsmoov.ProcessorLiveData)
  return false;
#undef DO_
}

void ProcessorLiveData::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:fmsmoov.ProcessorLiveData)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // float inL = 1;
  if (this->inl() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteFloat(1, this->inl(), output);
  }

  // float inR = 2;
  if (this->inr() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteFloat(2, this->inr(), output);
  }

  // float outL = 3;
  if (this->outl() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteFloat(3, this->outl(), output);
  }

  // float outR = 4;
  if (this->outr() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteFloat(4, this->outr(), output);
  }

  // @@protoc_insertion_point(serialize_end:fmsmoov.ProcessorLiveData)
}

::google::protobuf::uint8* ProcessorLiveData::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:fmsmoov.ProcessorLiveData)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // float inL = 1;
  if (this->inl() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteFloatToArray(1, this->inl(), target);
  }

  // float inR = 2;
  if (this->inr() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteFloatToArray(2, this->inr(), target);
  }

  // float outL = 3;
  if (this->outl() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteFloatToArray(3, this->outl(), target);
  }

  // float outR = 4;
  if (this->outr() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteFloatToArray(4, this->outr(), target);
  }

  // @@protoc_insertion_point(serialize_to_array_end:fmsmoov.ProcessorLiveData)
  return target;
}

size_t ProcessorLiveData::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:fmsmoov.ProcessorLiveData)
  size_t total_size = 0;

  // float inL = 1;
  if (this->inl() != 0) {
    total_size += 1 + 4;
  }

  // float inR = 2;
  if (this->inr() != 0) {
    total_size += 1 + 4;
  }

  // float outL = 3;
  if (this->outl() != 0) {
    total_size += 1 + 4;
  }

  // float outR = 4;
  if (this->outr() != 0) {
    total_size += 1 + 4;
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void ProcessorLiveData::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:fmsmoov.ProcessorLiveData)
  GOOGLE_DCHECK_NE(&from, this);
  const ProcessorLiveData* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const ProcessorLiveData>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:fmsmoov.ProcessorLiveData)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:fmsmoov.ProcessorLiveData)
    MergeFrom(*source);
  }
}

void ProcessorLiveData::MergeFrom(const ProcessorLiveData& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:fmsmoov.ProcessorLiveData)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.inl() != 0) {
    set_inl(from.inl());
  }
  if (from.inr() != 0) {
    set_inr(from.inr());
  }
  if (from.outl() != 0) {
    set_outl(from.outl());
  }
  if (from.outr() != 0) {
    set_outr(from.outr());
  }
}

void ProcessorLiveData::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:fmsmoov.ProcessorLiveData)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void ProcessorLiveData::CopyFrom(const ProcessorLiveData& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:fmsmoov.ProcessorLiveData)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ProcessorLiveData::IsInitialized() const {
  return true;
}

void ProcessorLiveData::Swap(ProcessorLiveData* other) {
  if (other == this) return;
  InternalSwap(other);
}
void ProcessorLiveData::InternalSwap(ProcessorLiveData* other) {
  std::swap(inl_, other->inl_);
  std::swap(inr_, other->inr_);
  std::swap(outl_, other->outl_);
  std::swap(outr_, other->outr_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata ProcessorLiveData::GetMetadata() const {
  protobuf_proto_2ffmsmoov_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_proto_2ffmsmoov_2eproto::file_level_metadata[kIndexInFileMessages];
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// ProcessorLiveData

// float inL = 1;
void ProcessorLiveData::clear_inl() {
  inl_ = 0;
}
float ProcessorLiveData::inl() const {
  // @@protoc_insertion_point(field_get:fmsmoov.ProcessorLiveData.inL)
  return inl_;
}
void ProcessorLiveData::set_inl(float value) {
  
  inl_ = value;
  // @@protoc_insertion_point(field_set:fmsmoov.ProcessorLiveData.inL)
}

// float inR = 2;
void ProcessorLiveData::clear_inr() {
  inr_ = 0;
}
float ProcessorLiveData::inr() const {
  // @@protoc_insertion_point(field_get:fmsmoov.ProcessorLiveData.inR)
  return inr_;
}
void ProcessorLiveData::set_inr(float value) {
  
  inr_ = value;
  // @@protoc_insertion_point(field_set:fmsmoov.ProcessorLiveData.inR)
}

// float outL = 3;
void ProcessorLiveData::clear_outl() {
  outl_ = 0;
}
float ProcessorLiveData::outl() const {
  // @@protoc_insertion_point(field_get:fmsmoov.ProcessorLiveData.outL)
  return outl_;
}
void ProcessorLiveData::set_outl(float value) {
  
  outl_ = value;
  // @@protoc_insertion_point(field_set:fmsmoov.ProcessorLiveData.outL)
}

// float outR = 4;
void ProcessorLiveData::clear_outr() {
  outr_ = 0;
}
float ProcessorLiveData::outr() const {
  // @@protoc_insertion_point(field_get:fmsmoov.ProcessorLiveData.outR)
  return outr_;
}
void ProcessorLiveData::set_outr(float value) {
  
  outr_ = value;
  // @@protoc_insertion_point(field_set:fmsmoov.ProcessorLiveData.outR)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

}  // namespace fmsmoov

// @@protoc_insertion_point(global_scope)
